pull_request_rules:
  - name: "Automatic merge when CI passes and approved"
    conditions:
      - "author=dependabot[bot]"
      - "check-success=dependency-review"
    actions:
      merge:
        method: merge