name: Delete old workflow runs
on:
  schedule:
    # Run weekly, at 00:00 on mondays.
    - cron: '0 0 * * 1'
jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5
      - name: Delete workflow runs
        shell: bash
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh run --limit 10 list --json databaseId  -q '.[].databaseId' | xargs -IID gh api "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID" -X DELETE
