name: Delete old workflow runs
on:
  schedule:
    - cron: '*/5 * * * *'
# Run monthly, at 00:00 on the 1st day of month.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Delete workflow runs
        shell: bash
        env:
           GH_TOKEN: ${{ github.token }}
        run: gh run --status failure --limit 1000 list --json databaseId  -q '.[].databaseId' |
                xargs -IID gh api \
                        "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID" \
                        -X DELETE
