name: Feature Test

on:
  push:
    branches:
      - feature/**
      - main

jobs:
  feature-test:
    uses: ./.github/workflows/feature-test.yml
    secrets:
      gh-email: ${{ secrets.GH_EMAIL }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      dev-hub-auth-url: ${{ secrets.DEV_HUB_AUTH_URL }}