name: Feature Test

on:
  push:
    branches:
      - feature/**
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'

concurrency:
  group: feature-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  feature-test:
    name: Feature Test

    uses: ./.github/workflows/feature-test.yml

    secrets: inherit