# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
  schedule:
    - cron: '0 0 * * 4'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run PMD
        uses: pmd/pmd-github-action@v1.4.1
        id: pmd
        with:
          version: '6.55.0'
          sourcePath: 'force-app'
          rulesets: 'rulesets/ruleset.xml'
          analyzeModifiedFilesOnly: false
      # Check for PMD violations and show Warning
      - name: Check for PMD violations
        if: steps.pmd.outputs.violations != 0
        run: |
          echo -e "\e[31mPMD VIOLATIONS ENCOUNTERED\e[0m"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif
