name: Production Release
on:
    workflow_dispatch:
jobs:
    feature-test:
        name: "Production Release"
        uses: '.github/workflows/prod-release.yml@main'
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.GITHUB_TOKEN }}"
