name: Production Release
on:
    workflow_dispatch:
jobs:
    feature-test:
        name: "Production Release"
        uses: Fatal1tyBarucco/GitHub-MuseLab-DX2/.github/workflows/release-2gp.yml@main
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.GITHUB_TOKEN }}"